### PR TITLE
feat: Add admin panel

### PR DESCRIPTION
**Pull request by Undermaken**
# 📚 Description
## What
This PR closes https://github.com/latina-in-tech/latina-in-tech.github.io/issues/28
It introduces a **new menu style** and the admin panel page

# 🖼 Screenshots/Recordings

## demo
https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/5a6ebfe8-532f-478b-8939-f2fb8c8350d5

https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/421530db-d0c7-4402-ae90-5a0fbdd153df

### CODE REVIEW

**Comment by coluzziandrea** [comment]
Great work! I did some changes:

- Fixed light/dark theme for some components, like this one:

Screenshot Capture - 2023-12-07 - 19-52-33


- Added github, twitter & personal website url for admins
- Fixed current route check in header (added router for that)
- Adds title for admin page
- Re-added menu items name for the mobile experience (there was too much empty space after icons)
Screenshot from 2023-12-07 19-53-39


the new experience is like that:
[Screencast from 08-12-2023 00:02:52.webm](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/12852000/30ebbe2f-5909-443f-b8e1-c59f27b55601)

**Review by coluzziandrea — APPROVED** [review]
@Undermaken feel free to merge this, also change colors again if you want 👯

**Comment by Undermaken** [comment]
> @Undermaken feel free to merge this, also change colors again if you want 👯 

Much better!!!!
Thank you! 👏👏

**Comment by Undermaken** [comment]
@coluzziandrea I can't merge. I guess because you didn't approve the last changes.

From me you can proceed with the merge directly!

**Comment by Undermaken** [comment]
@coluzziandrea sorry!
I noticed that I had forgotten this https://github.com/latina-in-tech/latina-in-tech.github.io/pull/60/commits/a1f3195b8d7a233d6854216763d50148e8d72edb
So you introduced `useRouter` to override that hard-coded value

I fixed the error and removed the usage of `useRouter`

Could you check if everything works as expected?

**Comment by coluzziandrea** [comment]
@Undermaken yes that's the expectation!!! Sorry I was but confused 🤔

**Review by coluzziandrea — APPROVED** [review]

**Pull request merged**
